branches:
  only: master
addons:
  apt:
    packages:
    - python3-requests
    - python3-yaml
before_script: chmod +x amy_add.sh
script: "./amy_add.sh"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
  - secure: O0oFtG98G15jfDW3vi57IfKT60L4PRIXwGe0/JC+P2pp1VFOOjjnSq2jzf0+pO+RoMVL9Wsb5MQ8qUMHzHOaky3/4EjsUFiflw+yZU3I8rrnXPhuELXfL3MzMPx5EUVZ/xD1nNdzxd7rjHuCBVjcLk8Jp4VFUeGhFPtRvg8gSxDIK8xHk128Cl67mL/bqzACHHqhnJpoV9JGORchgTVsKV5vn+K4caTwboQ2GSkYpl006cgGekOR7BaSDuKQyfQfTkxUhoCSlOVXoe0zMOA1Lbq43v1NwzztwQggw/3LPjjru0BszO4w7ZH4K2Mj3U5372zQjt1PktBWO9+zFVfwU2s/nbA7Y5ff2jHMEkzR4V+li9g0/CABJO60PfmtmDU8F+PmYpGJuxqdLOs/ENDUf3WN0JszcxTY3kjK2w7V6ngHjl1rJO6fEaARSovQ6BilOF1b8WPxJM+kd86A9q67MfWu3hPET79zJlHJmgWeiX3r98lEcw0/J856OIcc698ajQ1zZDFLwwkZ2KnEkeF4odQNtjyLlgM7eAJI3ciL3yPd5+rCgUKf49b+KhJXy5xyxogQ1gClMjf9ilieUaCdgu5AN7OcEJGzQewhudMKMykXUeUIgElU0gvHiVwcbgDzHrGX37ZEmHQuUi851tIW0zDpO6AbWFWBnlSogjxaf4k=
  - secure: JI52ItvyeTGn107kJMxoB6n8359k/WPNYdmYfL/X1+dZpW4cug3S3db90rGbnQx7x9kcZPF/J49TI9zwYDSr1qOfCEqEQ364zzgcvPryrAzwdvq8zWq2Y6ZE729jN5qgD8mRWXWO8hKxuOAT8PTKB6jfRZgxT2a4kHXnZxbnKpUuDIFbrtehNlEvLYVZLWH8mflxrivKi6HRWsj8ZRWJrB+c8yMk+zZm9Bkcedr2SWz9xthVAK4Z5T9ys5nyd0vn9hrTZTg71ug802RSwkEW3it1NJ7GrFFctSo/e/z2NzHaWN0Nvi/qHrd7Q52EGWajjJF7OuCFJzszFpKEguOJhzS/DeZbtrN/Mjn6JNsEb/B74cCjNLyGHGOcIzoFdAxCB+vjXEyaTMZloan3RnhmKoDPo8/WYOW19IlOc7xQOO/+WV4649XwT4DAWhkCi3sy1jv+RkX1WYmKhjsdgF/GaclJmmyejR5gJmPUCxVjHHHdhouE3VpqiBaA6Tq01Bm3hI+VdazcUxXJWDB7IgPkfx4ORUOcZZrzlB78m8UDYfU41FrKV1p1l46aY2icMSkLSc94qoPKDUEpOf3OUyUn9BYts4iaUYbqXsem7AGQDptd8TyAV54gppD1VdoiB+qiZ+55xoAS6gtRxSimpDdOt1R8uDkqlYAVP3p65ylF0NQ=
